### ISSUE TITLE
Add Java goody for traversing a binary tree post-order

### ISSUE THREAD

**Issue by miorel** [code-chronicles-code/leetcode-curriculum#173]
Can draw inspiration from the TypeScript goodies in #157 and the Java counterpart in #167.

**Comment by utsavatwork** [comment]
@miorel can you suggest me which ticket should I pick next? I am ok with either java or typescript.

**Comment by miorel** [comment]
Do you have some time for a quick call sometime? I think it will be easiest to discuss live. Send me an email (you can find it in `git log`) and we can plan something.
