### ISSUE TITLE
Create an `IterableDoubleStream` Java goody

### ISSUE THREAD

**Issue by miorel** [code-chronicles-code/leetcode-curriculum#183]
This would be the double-specific specialization of `IterableStream`, similar to the `IterableIntStream` introduced in #181.

**Comment by utsavatwork** [comment]
hey @miorel, I'd like to take this.

**Comment by miorel** [comment]
Sure! This issue entails creating another sub-directory in the `tools/adventure-pack/goodies/java/src` directory. It should be very similar to `iterable_int_stream` but instead be double-specific.

I haven't really documented how to set up the development environment, but at a high-level:
* If you have experience with Node.JS you can use `yarn` from the `tools` directory or from the `tools/adventure-pack` directory to set things up. (The main glue code for this project is in TypeScript/JavaScript.)
* If you search for "java" in `tools/adventure-pack/package.json` you will see some of the Java-specific commands there.
* If you're only developing Java code, you can also ignore all the JavaScript stuff, and use Gradle directly in the `tools/adventure-pack/goodies/java` directory. Notably, if you run `./gradlew compileJava` in that directory that will attempt to compile the Java code.

If I can be of any assistance, let me know, I'm happy to jump on a call sometime.

**Comment by utsavatwork** [comment]
ok. I'll try to setup dev environment first. will update you. Thanks!

**Comment by utsavatwork** [comment]
> ok. I'll try to setup dev environment first. will update you. Thanks!

hey @miorel, I believe I've setup the dev environment successfully. Just to confirm with you, I cloned the repository, installed yarn and ran "yarn install" command in tools directory. I hope it's the right way.

So, am I good to go for the actual changes related to the issue? Also, let me know any other things which I as a contributor should know (if any).

Thanks!

**Comment by miorel** [comment]
Nothing specific, the general practices of open source contributions apply 😄

**Comment by utsavatwork** [comment]
> Nothing specific, the general practices of open source contributions apply 😄 
> 
> Feel free to send a pull request when you feel ready, or let me know if I can help with anything.

All right! 🙂
Thanks.

**Comment by utsavatwork** [comment]
@miorel I am not been able to push to the remote.
![screen](https://github.com/user-attachments/assets/be910ed7-df58-4c79-8576-b0bb49d314b1)

**Comment by miorel** [comment]
You will have to use the workflow of creating a fork of the repository and creating a pull request through the fork. I recommend installing the [GitHub command-line interface](https://docs.github.com/en/github-cli/github-cli/about-github-cli), which can do the heavy lifting for you. It will make a `gh` command available, then you should be able to simply run `gh pr create` and follow the prompts in the terminal.

See also [the pull request docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request?tool=cli&platform=windows).

**Comment by utsavatwork** [comment]
@miorel Can you check the PR https://github.com/code-chronicles-code/leetcode-curriculum/pull/218
