### ISSUE TITLE
Add Kotlin goody for traversing a binary tree in level order

### ISSUE THREAD

**Issue by miorel** [code-chronicles-code/leetcode-curriculum#314]
For inspiration, take a look at the TypeScript goody added in #189, currently located at [`workspaces/adventure-pack/goodies/typescript/traverseLevelOrder/index.ts`](../tree/main/workspaces/adventure-pack/goodies/typescript/traverseLevelOrder/index.ts).

**Comment by yulianka** [comment]
This issue already exists #193 .

**Comment by miorel** [comment]
> This issue already exists #193 .

Oops, good catch. Guess we can rebrand this as Kotlin 😅

**Comment by willmadison** [comment]
I'm happy to take a look at this if no one else is already on it :)

**Comment by miorel** [comment]
That'd be amazing, @willmadison, thank you!
