### ISSUE TITLE
Add tests for `squashWhitespace` utility

### ISSUE THREAD

**Issue by miorel** [code-chronicles-code/leetcode-curriculum#352]
Add a file `workspaces/util/src/__tests__/squashWhitespace-test.ts`, for testing the `squashWhitespace` utility.

To see some PRs that add tests, take a look at #288 and #290 for inspiration.

**Comment by Ma-hawaj** [comment]
Can you assign this to me ?

**Comment by miorel** [comment]
Sure, thank you for working on it! 😄
